name: environment variables
on: push
jobs:
  repo-name:
    env:
      APPLICATION: '${{github.event.repository.name}}'
      DBUSERNAME: '$APPLICATION'-ci
      DBPASSWORD: action-ci
      DBNAME: action-ci
      DBHOST: 127.0.0.1
      FILESDIR: files
     
    runs-on: ubuntu-latest
    strategy:
      matrix:
          REPO: [ "${{ github.event.repository.name }}"]
    steps:
     - name: $APPLICATION
       run: |
        echo  $DBUSERNAME
     
